### ISSUE TITLE
TCGA data - TCGAbiolinks

### ISSUE THREAD

**Issue by oztoprak-f** [BioinformaticsFMRP/TCGAbiolinks#121]
I want to know the difference between TCGA data we download from firebrowse.org and TCGA data we download with GDCdownload function. 
The things i realized;
- Categorization is different between two. At firebrowse we can download results of mRNASeq for example. With GDCdownload we can get "Gene expression quantification, isoform expression.." so on.
- Firebrowse data has 1 more column and raw. GDCdownloaded matrix has the gene names as rownames, TCGA barcode as colnames. At Firebrowse data, gene.id is a column and they have data information (gene.id, normalized_count) along the first row. 
- I downloaded by both, firebrowse data is .txt file. I read it by "read.table", saved "as.matrix", adjusted rownames, deleted first row and column, but couldn't do TCGA analysis, it gave different error messages. Does it makes sense to analyze firebrowse data with TCGAbiolinks?
- It seems for TCGAbiolinks analysis, getting the data with its' functions download data suitable for further analysis, while firebrowse data can be analyzed with different packages.

Thanks in advance.

**Comment by tiagochst** [comment]
Hello,

Sorry for the delay.

The differences are:
- Sources:
  - Firehose data has mainly open access data level 3 and level 4 (i.e. GISTIC results). And, If I'm not wrong, the data available in firehose is still the data aligned to hg19. The categorization follows the old TGCA Categorization.

  - TCGAbiolinks access GDC, which will give you the option to download either the data aligned to hg38 (harmonized) or hg19 legacy database.
- Objects created:
  - The flat table can be outputted from TCGAbiolinks using in the `GDCpreapre` function `SummarizedExperiment = FALSE`, otherwise the R/Bioconductor object will be a SummarizedExperiment [More information](http://bioconductor.org/packages/release/bioc/vignettes/SummarizedExperiment/inst/doc/SummarizedExperiment.html) (see code and figures below)
- Firehose data with TCGAbiolinks:
  - They are supposed to be the same data. But you will have to prepare the firehose data into a SummarizedExperiment object to use our functions. Otherwise, I recommend using packages we import directly as they might give you the option to work directly with a matrix. We just created this wrapper functions to be easier to analyze the data prepared. But this might not be the best solution for everyone as some people prefers to do their own normalization or use other packages to analyze the data.

- Packages to be analyzed:
  - Some package supports the SummarizedExperiment such as DESeq2 (see example below). Several of our functions uses a SummarizedExperiment object as input. 

### Data frame vs Summarized Experiment
```
library(TCGAbiolinks)
query.exp <- GDCquery(project = "TCGA-LUSC",
                      data.category = "Transcriptome Profiling",
                      data.type = "Gene Expression Quantification", 
                      workflow.type = "HTSeq - FPKM-UQ",
                      barcode = c("TCGA-34-5231-01","TCGA-77-7138-01"))
GDCdownload(query.exp)
exp <- GDCprepare(query = query.exp,
                  save = TRUE, 
                  save.filename = "Exp_LUSC.rda",
                  summarizedExperiment = FALSE)
head(exp)
exp <- GDCprepare(query = query.exp,
                  save = TRUE, 
                  save.filename = "Exp_LUSC.rda",
                  summarizedExperiment = TRUE)
exp
```
<img width="1348" alt="screen shot 2017-07-31 at 6 22 32 pm" src="https://user-images.githubusercontent.com/145529/28805225-489a32a0-761d-11e7-9a3d-82e1861b9c4b.png">

### Working with different packages
http://bioconductor.org/packages/release/bioc/vignettes/DESeq2/inst/doc/DESeq2.html#summarizedexperiment-input
```
library("TCGAbiolinks")
library("DESeq2")
query.exp <- GDCquery(project = "TCGA-LUSC",
                      data.category = "Transcriptome Profiling",
                      data.type = "Gene Expression Quantification", 
                      workflow.type = "HTSeq - Counts",
                      barcode = c("TCGA-34-5231-01","TCGA-77-7138-01"))
GDCdownload(query.exp)
se <- GDCprepare(query = query.exp,
                  save = TRUE, 
                  save.filename = "Exp_LUSC.rda",
                  summarizedExperiment = TRUE)
ddsSE <- DESeqDataSet(se, design = ~ cigarettes_per_day)
ddsSE

```
