### ISSUE TITLE
Data discrepancies on certain indications when running survival analysis on TCGA

### ISSUE THREAD

**Issue by kikichang** [BioinformaticsFMRP/TCGAbiolinks#124]
Hi I am trying to do survival analysis on TCGA data using TCGAanalyze_survival(), clustering by gene expression value. I noticed that there's some difference between the number of patients in each group and the number of patients at risk starting at day 0 when analyzing breast cancer patient. This issue seems to happen for most if not all genes that I looked at for Breast Cancer and Bladder Cancer. But when I ran the same code for ACC indication, I didn't get the same error. I am wondering if there's some pre-processing steps that I am missing or this is an indication-specific issue. Thanks.
```
library(TCGAbiolinks)
library(SummarizedExperiment)

#download summarized experiment object BRCA
query <- GDCquery(project= "TCGA-BRCA",
                  data.category = "Gene expression",
                  data.type = "Gene expression quantification",
                  platform = "Illumina HiSeq",
                  file.type  = ".rsem.genes.normalized_results",
                  experimental.strategy = "RNA-Seq",
                  legacy = TRUE)

GDCdownload(query)
save(data, file="BRCA.RData")

#a summarized experiment object (BRCA) is loaded as 'data'
load("BRCA.RData")

#select gene to look at 
gene <- "A1BG"

#get the expression data of the selected gene
exp <- assay(data)[rownames(data) == gene,]

#sort the expression data based on the expression value; get the median value
cut <- max(sort(exp)[1:(length(exp) * 0.5)])

colData(data)[exp < cut,"expression"] <- "Low Expression"
colData(data)[exp >= cut,"expression"] <- "High Expression"

TCGAanalyze_survival(colData(data), clusterCol = "expression" ,pvalue = TRUE, risk.table = TRUE, conf.int = TRUE)
```
The plot generated can be found below.
[survival.brca.pdf](https://github.com/BioinformaticsFMRP/TCGAbiolinks/files/1183627/survival.brca.pdf)

When I run the same code with ACC data using the same download method and looking at the same gene, I don't have the discrepancy issue. (see below) 

[survival.acc.pdf](https://github.com/BioinformaticsFMRP/TCGAbiolinks/files/1183628/survival.acc.pdf)

**Comment by tiagochst** [comment]
Hello, 

I believe there are problems with the clinical data. I'm traveling today so I won't be able to dig up very deeply. But there are 4 cases with  inconsistencies in the clinical data below. Which is why we had that problem. Unfortunately, I was not considering  this problems in the data when we add the number of samples in the label. I change it to consider there might be problems and give a warning to the user that those will not be used.


But so far this too cases having missing values for some fields: "TCGA-OL-A66H-01A"

<img width="962" alt="screen shot 2017-07-28 at 4 28 14 pm" src="https://user-images.githubusercontent.com/145529/28735105-d1216724-73b1-11e7-94be-62b49774d164.png">

For case "TCGA-BH-A0B2-01A" does not have any clinical indexed data:
<img width="1127" alt="screen shot 2017-07-28 at 4 30 47 pm" src="https://user-images.githubusercontent.com/145529/28735195-2d5819e8-73b2-11e7-97bc-f192e0ba82f8.png">

There are some cases with negative values . for days: "TCGA-PL-A8LV-01A" "TCGA-A8-A082-01A
<img width="950" alt="screen shot 2017-07-28 at 4 33 33 pm" src="https://user-images.githubusercontent.com/145529/28735288-88d4062e-73b2-11e7-991c-39dde55f7dd3.png">
"

<img width="1099" alt="screen shot 2017-07-28 at 4 33 03 pm" src="https://user-images.githubusercontent.com/145529/28735273-78f885ae-73b2-11e7-8214-74be1cf4b624.png">

**Comment by kikichang** [comment]
After filtering out those invalid clinical data, it seems to work fine.  Thanks!

**Comment by tiagochst** [comment]
@kikichang  Below are GDC answer about these data:

> It took a little research but we got to the bottom of things.  Here is what they came back with - (cases with a negative number of days to follow-up)
"... there are about a dozen of these cases throughout the entire TCGA cohort (~0.1% of all cases), and the TCGA analysis working groups handled them in a couple of ways. Some of them removed them from survival analysis all together and others censored their number of days to 0. These decisions really depended on the  group. There are also a bunch of other cases whose days to follow-up is 0 - some of the groups removed these from analysis as well. There is a TCGA paper coming out soon with methods on how to handle all of these cases. We should consider using it to calculate survival."

> "... asking why the negative number of days to follow-up exists, that has to do with sites who never see the patient after the tumor is removed. They might have known the date of surgery (which would be the last date the patient was seen by that institution), but the specific pathologic diagnosis could have been a while after the patient went home. Most of these cases are international, often coming from countries where the standard of care is quite different. Others are from tissue banks where direct contact with the patient was not possible."

**Comment by kikichang** [comment]
@tiagochst   thanks!
