### ISSUE TITLE
Problem Downloading Clinical Data

### ISSUE THREAD

**Issue by kvougas** [BioinformaticsFMRP/TCGAbiolinks#14]
When I ran the following:
`query <- GDCquery(project = "TCGA-OV", data.category = "Clinical")
GDCdownload(query,directory = "~/Projects/GDC/Clinical")`

I got the following error:

**Accessing GDC. This might take a while...
GDCdownload will download: 31.370846 MB compressed in a tar.gz file
Downloading as: Mon_Aug_22_09_22_25_2016.tar.gz
  |======================================================================================| 100%
/bin/tar: This does not look like a tar archive

gzip: stdin: not in gzip format
/bin/tar: Child returned status 1
/bin/tar: Error is not recoverable: exiting now
[1] 2
Error in GDCdownload(query, directory = "~/Projects/GDC/Clinical") : 
  There was an error in the download process, please execute it again
In addition: Warning message:
In untar(name) :
  ‘/bin/tar -xf 'Mon_Aug_22_09_22_25_2016.tar.gz'’ returned error code 2**

The same error is also generated with:
"TCGA-LGG" & "TCGA-LIHC"

**Comment by tiagochst** [comment]
Hi,

I was able to run the code, could you send me your sessionInfo(), also, could you try to run 
 `query <- GDCquery(project = "TCGA-OV", data.category = "Clinical")
  GDCdownload(query)`
Maybe it is related to the ~, but it is working in linux.

![screenshot from 2016-08-22 13-15-08](https://cloud.githubusercontent.com/assets/145529/17862122/426b8652-686a-11e6-9b91-4b77caadde0d.png)

**Comment by kvougas** [comment]
I also ran it under Ubuntu 16.04LTS. I think it  was a glitch with the GDC. Now I reran it, everything was fine.

Thanks

**Comment by TBradley27** [comment]
Hello,

I am afraid that this is still an issue, and all of the recommendations in this thread do not successfully resolve this issue.

I have tested this on `R version 4.3.1` with `TCGAbiolinks version 2.30.0`

I am receiving the same/similar error messages to the OP

Can I request please that this issue is reopened?

**Comment by TBradley27** [comment]
Hello again,

The issue is due to users trying to attempt download of controlled data without using a token. The result is that a file is downloaded into the user's directory with the file extension `.tar.gz` which is not actually a compressed archive file.

Despite the file extension, this is actually a plain text file with the following contents:

`{"message":"Your token is invalid or expired. Please get a new token from GDC Data Portal."}`

To prevent confusion, I believe that there is a better of catching/managing this error, and informing users of the true nature of the problem
