### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by zhaojunpeng1991** [BioinformaticsFMRP/TCGAbiolinks#248]
centos 7.1 
R 3.5.0
when I used the command devtools::install_github(repo = "BioinformaticsFMRP/TCGAbiolinks",dependencies = T) to install the TCGAbiolinks, It run error.
Installation failed: An unknown option was passed in to libcurl

I don't known how to do? 
Can you tele me the way to install this packages?

Thank you!

**Comment by Melkiades** [comment]
It seems your problem is related to `devtools` and not `TCGAbiolinks`. I would try to install `libcurl` correctly  with `yum reinstall libcurl`. Anyway, before posting any issues, I recommend you to check if the problem has been addressed somewhere before. Indeed, I would have followed [this](https://github.com/r-lib/devtools/issues/1682#issuecomment-365399988) issue/answer before posting here.
