### ISSUE TITLE
GDCquery Error

### ISSUE THREAD

**Issue by mxrcx** [BioinformaticsFMRP/TCGAbiolinks#256]
I have installed the lates TCGAbiolinks version from your GitHub Repo. But I still get this error message when I try to use GDCquery.

query <- TCGAbiolinks::GDCquery(project = "TCGA-BRCA",
                      data.category = "Gene expression",
                      data.type = "Gene expression quantification",
                      experimental.strategy = "RNA-Seq",
                      platform = "IlluminaHiSeq_RNASeq",
                      file.type = "results",
                      barcode = c("TCGA-E9-A1NG-11A-52R-A14M-07"),
                      legacy = TRUE)

--------------------------------------
o GDCquery: Searching in GDC database
--------------------------------------
Genome of reference: hg19
--------------------------------------------
oo Accessing GDC. This might take a while...
--------------------------------------------
ooo Project: TCGA-BRCA
Error:  Error in getURL(url, fromJSON, timeout(600), simplifyDataFrame = TRUE): 'getURL()' failed:
  URL: https://api.gdc.cancer.gov/legacy/files/?pretty=true&expand=cases.samples.portions.analytes.aliquots,cases.project,center,analysis&size=15492&filters=%7B%22op%22:%22and%22,%22content%22:[%7B%22op%22:%22in%22,%22content%22:%7B%22field%22:%22cases.project.project_id%22,%22value%22:[%22TCGA-BRCA%22]%7D%7D,%7B%22op%22:%22in%22,%22content%22:%7B%22field%22:%22files.data_category%22,%22value%22:[%22Gene%20expression%22]%7D%7D,%7B%22op%22:%22in%22,%22content%22:%7B%22field%22:%22files.data_type%22,%22value%22:[%22Gene%20expression%20quantification%22]%7D%7D]%7D&format=JSON
  error: HTTP error 504.

We will retry to access GDC!

**Comment by VaradanLab** [comment]
Getting the same error. Is there any workaround. 
BRCA_Expression_Samps <- GDCquery(project = "TCGA-BRCA",data.category = "Gene expression",data.type = "Gene expression quantification",legacy=T, file.type = "normalized_results",experimental.strategy = "RNA-Seq")
--------------------------------------
o GDCquery: Searching in GDC database
--------------------------------------
Genome of reference: hg19
--------------------------------------------
oo Accessing GDC. This might take a while...
--------------------------------------------
ooo Project: TCGA-BRCA
Error:  Error in getURL(url, fromJSON, timeout(600), simplifyDataFrame = TRUE): 'getURL()' failed:
  URL: https://api.gdc.cancer.gov/legacy/files/?pretty=true&expand=cases.samples.portions.analytes.aliquots,cases.project,center,analysis&size=15492&filters=%7B%22op%22:%22and%22,%22content%22:[%7B%22op%22:%22in%22,%22content%22:%7B%22field%22:%22cases.project.project_id%22,%22value%22:[%22TCGA-BRCA%22]%7D%7D,%7B%22op%22:%22in%22,%22content%22:%7B%22field%22:%22files.data_category%22,%22value%22:[%22Gene%20expression%22]%7D%7D,%7B%22op%22:%22in%22,%22content%22:%7B%22field%22:%22files.data_type%22,%22value%22:[%22Gene%20expression%20quantification%22]%7D%7D]%7D&format=JSON
  error: HTTP error 504.

We will retry to access GDC!
Error: lexical error: invalid char in json text.
                                       <html>  <head><title>504 Gatewa
                     (right here) ------^

**Comment by lhhaoliu** [comment]
exactly the same issue here...

and the weird part is this only happens to TCGA-BRCA, all other data can be downloaded without any issues...

my code that cause this issue:

  query <- GDCquery(project="TCGA-BRCA",   
                    data.category = "Gene expression",
                    data.type = "Gene expression quantification",
                    platform = "Illumina HiSeq",
                    file.type  = ".rsem.genes.normalized_results",
                    experimental.strategy = "RNA-Seq",
                    legacy = TRUE) 

error message got below:
==================================================
--------------------------------------
o GDCquery: Searching in GDC database
--------------------------------------
Genome of reference: hg19
--------------------------------------------
oo Accessing GDC. This might take a while...
--------------------------------------------
ooo Project: TCGA-BRCA
Error:  Error in getURL(url, fromJSON, timeout(600), simplifyDataFrame = TRUE): 'getURL()' failed:
  URL: https://api.gdc.cancer.gov/legacy/files/?pretty=true&expand=cases.samples.portions.analytes.aliquots,cases.project,center,analysis&size=15492&filters=%7B%22op%22:%22and%22,%22content%22:[%7B%22op%22:%22in%22,%22content%22:%7B%22field%22:%22cases.project.project_id%22,%22value%22:[%22TCGA-BRCA%22]%7D%7D,%7B%22op%22:%22in%22,%22content%22:%7B%22field%22:%22files.data_category%22,%22value%22:[%22Gene%20expression%22]%7D%7D,%7B%22op%22:%22in%22,%22content%22:%7B%22field%22:%22files.data_type%22,%22value%22:[%22Gene%20expression%20quantification%22]%7D%7D,%7B%22op%22:%22in%22,%22content%22:%7B%22field%22:%22files.platform%22,%22value%22:[%22Illumina%20HiSeq%22]%7D%7D]%7D&format=JSON
  error: HTTP error 504.

We will retry to access GDC!
Error: lexical error: invalid char in json text.
                                       <html>  <head><title>504 Gatewa
                     (right here) ------^

**Comment by lhhaoliu** [comment]
wonder if this is due to TCGA-BRCA's sheer size...

**Comment by tiagochst** [comment]
@Henrik86 Please, could you send the query you used?

**Comment by Henrik86** [comment]
Hi Tiago, the query was:

 query.exp.hg19.raw <- GDCquery(project = "TCGA-SKCM",data.category = "Gene expression",data.type = "Gene expression quantification", experimental.strategy = "RNA-Seq",platform = "Illumina HiSeq",file.type = "results",legacy = TRUE)

However, it is working again since thins morning.
Thanks a lot!

**Comment by fiwong** [comment]
Hi. I got the same issue with 504 server error

> query.TCGASTAD.NIPBL.hg19 <- GDCquery(project = "TCGA-STAD",
+                   data.category = "Gene expression",
+                   data.type = "Gene expression quantification",
+                   platform = "Illumina HiSeq", 
+                   file.type  = "normalized_results",
+                   experimental.strategy = "RNA-Seq",
+                   legacy = TRUE)
--------------------------------------
o GDCquery: Searching in GDC database
--------------------------------------
Genome of reference: hg19
--------------------------------------------
oo Accessing GDC. This might take a while...
--------------------------------------------
ooo Project: TCGA-STAD
Error:  Error in getURL(url, fromJSON, timeout(600), simplifyDataFrame = TRUE): 'getURL()' failed:
  URL: https://api.gdc.cancer.gov/legacy/files/?pretty=true&expand=cases.samples.portions.analytes.aliquots,cases.project,center,analysis,cases.samples&size=6943&filters=%7B%22op%22:%22and%22,%22content%22:[%7B%22op%22:%22in%22,%22content%22:%7B%22field%22:%22cases.project.project_id%22,%22value%22:[%22TCGA-STAD%22]%7D%7D,%7B%22op%22:%22in%22,%22content%22:%7B%22field%22:%22files.data_category%22,%22value%22:[%22Gene%20expression%22]%7D%7D,%7B%22op%22:%22in%22,%22content%22:%7B%22field%22:%22files.data_type%22,%22value%22:[%22Gene%20expression%20quantification%22]%7D%7D,%7B%22op%22:%22in%22,%22content%22:%7B%22field%22:%22files.platform%22,%22value%22:[%22Illumina%20HiSeq%22]%7D%7D,%7B%22op%22:%22in%22,%22content%22:%7B%22field%22:%22files.tags%22,%22value%22:[%22normalized%22]%7D%7D]%7D&format=JSON
  error: HTTP error 504.

We will retry to access GDC!


This happens since this morning

**Comment by dtopouza** [comment]
Hello,

I am having the same issue with the following query:

query <- GDCquery(barcode = barcode_list,
                  project = "TCGA-OV",
                  data.category = "Raw sequencing data",
                  data.type = "Aligned reads",
                  experimental.strategy = "WGS",
                  legacy = TRUE,
                  sample.type = c("Primary solid Tumor")
)

--------------------------------------
o GDCquery: Searching in GDC database
--------------------------------------
Genome of reference: hg19
--------------------------------------------
oo Accessing GDC. This might take a while...
--------------------------------------------
ooo Project: TCGA-OV
Error:  Error in getURL(url, fromJSON, timeout(600), simplifyDataFrame = TRUE): 'getURL()' failed:
  URL: https://api.gdc.cancer.gov/legacy/files/?pretty=true&expand=cases.samples.portions.analytes.aliquots,cases.project,center,analysis,cases.samples&size=5885&filters=%7B%22op%22:%22and%22,%22content%22:[%7B%22op%22:%22in%22,%22content%22:%7B%22field%22:%22cases.project.project_id%22,%22value%22:[%22TCGA-OV%22]%7D%7D,%7B%22op%22:%22in%22,%22content%22:%7B%22field%22:%22files.data_category%22,%22value%22:[%22Raw%20sequencing%20data%22]%7D%7D,%7B%22op%22:%22in%22,%22content%22:%7B%22field%22:%22files.data_type%22,%22value%22:[%22Aligned%20reads%22]%7D%7D,%7B%22op%22:%22in%22,%22content%22:%7B%22field%22:%22cases.samples.sample_type%22,%22value%22:[%22Primary%20Tumor%22]%7D%7D]%7D&format=JSON
  error: HTTP error 504.

We will retry to access GDC!
Error: lexical error: invalid char in json text.
                                       <html>  <head><title>504 Gatewa
                     (right here) ------^

This issue has persisted since yesterday and after multiple fresh installations from your repository.

**Comment by AljoLe** [comment]
Please format your code according to this [reference](https://help.github.com/articles/creating-and-highlighting-code-blocks/), otherwise everybody's eyes will bleed.

Thank you

**Comment by tiagochst** [comment]
@dtopouza for some reason the GDC API was not able to return all the results of the query.  I updated the code to improve the query. It should be working now.

Could you please, install the updated version? 
`devtools::install_github("BioinformaticsFMRP/TCGAbiolinks")`
