### ISSUE TITLE
Error:"experimental.strategy" is missing, with no default

### ISSUE THREAD

**Issue by thecourseraway** [BioinformaticsFMRP/TCGAbiolinks#297]
I was trying to download TCGA-LAML transcriptome profiling data using the following:
query <- GDCquery(project = "TCGA-LAML", 
                  data.category = "Transcriptome Profiling", 
                  data.type = "Gene Expression Quantification",
                  experimental.strategy= "RNA-Seq", 
                  workflow.type = "HTSeq - Counts", 
                  sample.type = c("Primary solid Tumor"))
But every time it returns with the following error message:
Error in getGDCquery(project = proj, data.category = data.category, data.type = data.type,  : 
  argument "experimental.strategy" is missing, with no default.
I downloaded data for other projects with same code and it worked fine. Restarting R, reloading packages etc didn't help.

**Comment by tiagochst** [comment]
Hi, there was a missing argument in the inside function. However, it was triggered because your query does not find any results.

<img width="1197" alt="screen shot 2019-03-05 at 1 48 08 pm" src="https://user-images.githubusercontent.com/145529/53821960-8a7d2600-3f4d-11e9-976b-7eba8fcdd163.png">

There is no Primary solid Tumor for TCGA-LAML. The sample types are in the screenshot above.

**Comment by thecourseraway** [comment]
Thanks!! Oh yes offcourse, since its hematopoietic cancer. Worked fine now.
