### ISSUE TITLE
Problems with TCGAanalyze_Preprocessing()

### ISSUE THREAD

**Issue by AndreVidas** [BioinformaticsFMRP/TCGAbiolinks#34]
Hi TCGAbiolinks!

I have encountered problems with TCGAanalyze_Preprocessing() for a particular user on our server. The person is using TCGAbiolinks_2.1.13. When running the function we get the following error message:

Error in assay(object, datatype) :
  'assay(<RangedSummarizedExperiment>, i="character", ...)' invalid subscript 'i'
'i' not in names(assays(<RangedSummarizedExperiment>))
In addition: Warning message:
In data.row.names(row.names, rowsi, i) :
  some row.names duplicated: 11,78,80,84,111,119 --> row.names NOT used

Have you experienced this error before? The error does not occur when I'm running TCGAanalyze_Preprocessing() on my user-account. I have an older version of TCGAbiolinks (2.1.6), so maybe there is something wrong with the function in the new version of TCGAbiolinks? (We use the same version of SummarizedExperiment: 1.3.82)

Best,
André

**Comment by tiagochst** [comment]
Hi Andre,

Antonio made a change recently in the code. There is a new argument called "datatype". I just add a commit to deal if the problem. The problem is that name of the assay in the harmonized and legacy database are "raw_counts" and "raw_count". This "s" is the problem.

Otherwise, this would solve:
`dataPrep <- TCGAanalyze_Preprocessing(object = lgg.exp,cor.cut = 0.6, datatype = "raw_count)`

Best regards,
Tiago

**Comment by AndreVidas** [comment]
Al right, thank you so much!
