### ISSUE TITLE
TCGAbiolinks, GDCprepare: numbers of columns of arguments do not match

### ISSUE THREAD

**Issue by bugkillsme** [BioinformaticsFMRP/TCGAbiolinks#367]
Hi,
I am trying to use GDCprepare to prepare data from the 'TCGA-COAD' project. But it throws an error "Error in rbind(deparse.level, ...) : 
  numbers of columns of arguments do not match". I read the previous related issues about this problem and updated TCGAbiolinks with 'BiocManager::install("BioinformaticsFMRP/TCGAbiolinks")', but it still did not work. Can anyone help? Thanks in advance. I am really in a hurry.

**Comment by tiagochst** [comment]
Please, could you send the complete code so I can debug the problem ?

**Comment by AimSchina** [comment]
Hi, I am having the same issue when I am trying to get solid Tissue Normal HTSeq-FPKM-UQ data. I use the following code:
`
library(TCGAbiolinks)
library(SummarizedExperiment)
tcga_dir <- '/my/data/path/'
download_htseq_solidNormaldata <- function(selectedcancer){
  print(selectedcancer)
  query <- GDCquery(
    project = selectedcancer,
    data.category = "Transcriptome Profiling",
    data.type = "Gene Expression Quantification",
    sample.type = "Solid Tissue Normal",
    workflow.type = "HTSeq - FPKM-UQ")
  
  
  if (is.null(query)){
    print(paste0("No FPKM-UQ data of solid normal tissue for ", selectedcancer))
  }else{
    GDCdownload(query)
    data <- GDCprepare(query)
    clin <- colData(data)
    df_all <- assay(data)
    save(df_all,clin,file=paste0(tcga_dir, selectedcancer,"_RNASeq","FPKM_UQ",".RData"))
  }
  
  
}

tcga_projects <-TCGAbiolinks:::getGDCprojects()$project_id
mycancertypes <- tcga_projects[grepl("^TCGA-",tcga_projects)] # total 33

download_all <- sapply(mycancertypes[order(mycancertypes)],function(x) download_htseq_solidNormaldata(selectedcancer=x))
`

Thank you!

**Comment by bads752** [comment]
Hi, I also having the same problem with GDCprepare() function. Even the example at 'http://bioconductor.org/packages/release/bioc/vignettes/TCGAbiolinks/inst/doc/casestudy.html' is giving the 'numbers of columns of arguments do not match' issue:

`library(SummarizedExperiment)
library(TCGAbiolinks)
query.exp <- GDCquery(project = "TCGA-BRCA", 
legacy = TRUE,
data.category = "Gene expression",
data.type = "Gene expression quantification",
platform = "Illumina HiSeq", 
file.type = "results",
experimental.strategy = "RNA-Seq",
sample.type = c("Primary solid Tumor","Solid Tissue Normal"))
GDCdownload(query.exp)
brca.exp <- GDCprepare(query = query.exp, save = TRUE, save.filename = "brcaExp.rda")`

However, GDCprepare() works fine if  'summarizedExperiment = FALSE'. Hence I believe that the problem lies with the SummarizedExperiment package. I have just checked their github page at https://github.com/Bioconductor/SummarizedExperiment/tree/master/R, and they did change the SummarizedExperiment-class.R file last month. At https://github.com/Bioconductor/SummarizedExperiment/commit/41b87212b2a1f02fc1d587d8dc0d0a536659808a we can see the implemented changes:

`setReplaceMethod("colData", c("SummarizedExperiment", "NULL"),
    function(x, ..., value)
{
    value <- S4Vectors:::make_zero_col_DataFrame(ncol(x))
    value <- new2("DFrame", nrows=ncol(x), rownames=colnames(x), check=FALSE)
    BiocGenerics:::replaceSlots(x, colData=value, check=FALSE)
})`

Apparently the colnames are begin set to NULL, so that might explain the problem with the colnumber and why GDCprepare function works when the summrizedExperiment is set to NULL.
I hope this might help to solve the issue.

Thank you!

**Comment by tiagochst** [comment]
@AimSchina This is what I get with your code: http://rpubs.com/tiagochst/bug367.

I had an uncommitted bugfix that I forgot to commit. Maybe that was the reason it was working for me. Could you update the package from github and check again, please? 

Running the following code should work  `BiocManager::install("BioinformaticsFMRP/TCGAbiolinks")`

**Comment by tiagochst** [comment]
@bads752  Please, could you update the package from github with `BiocManager::install("BioinformaticsFMRP/TCGAbiolinks")` ?

Also, GDC changed `Primary solid Tumor` to `Primary Tumor`.

```
library(SummarizedExperiment)
library(SummarizedExperiment)
query.exp <- GDCquery(project = "TCGA-BRCA",
                      legacy = TRUE,
                      data.category = "Gene expression",
                      data.type = "Gene expression quantification",
                      platform = "Illumina HiSeq",
                      file.type = "results",
                      experimental.strategy = "RNA-Seq",
                      sample.type = c("Primary Tumor","Solid Tissue Normal"))
GDCdownload(query.exp,files.per.chunk = 100)
brca.exp <- GDCprepare(query = query.exp, save = TRUE, save.filename = "brcaExp.rda")
```

**Comment by bads752** [comment]
Hello Tiago,

I just finished updating the package and running the code above, it worked like a charm!

I was aware that GDC changed 'Primary solid Tumor' to 'Primary Tumor', i just forgot to change code that I copied and pasted from the manual in my rush.

Thank you so much for your time!

**Comment by AimSchina** [comment]
Hi Tiago,

thank you, working fine now!

**Comment by bugkillsme** [comment]
Hi Tiago,
It's working now, thanks a lot for your hard work.


Best,
Qian







At 2019-11-24 15:30:00, "Tiago Chedraoui Silva" <notifications@github.com> wrote:


Please, could you send the complete code so I can debug the problem ?
