### ISSUE TITLE
GDCquery no disease.type parameter?

### ISSUE THREAD

**Issue by Liripo** [BioinformaticsFMRP/TCGAbiolinks#446]
Hello:
I would like to ask how to filter according to the type of disease. It has disease.type on GDC.
Thank you!

**Comment by tiagochst** [comment]
We don't have that option. We use project ID.

You can ue the function `getGDCprojects()` to get projects information. Otherwise you might be able to use https://bioconductor.org/packages/GenomicDataCommons/

<img width="781" alt="Screen Shot 2021-07-16 at 3 50 35 PM" src="https://user-images.githubusercontent.com/145529/126001398-9941299b-73c8-4a4b-996b-9a5acd4caf7e.png">
