### ISSUE TITLE
TCGAbiolinksGUI does not work in R>4.2

### ISSUE THREAD

**Issue by fkgruber** [BioinformaticsFMRP/TCGAbiolinks#568]
The GUI is not opening and I'm getting error:
` Error in if: the condition has length > 1`

This has to do with recent change in R 4.2:
https://cran.r-project.org/doc/manuals/r-release/NEWS.pdf
> Calling while() or if() statements with a condition of length greater than one gives an error rather than a warning

**Comment by tiagochst** [comment]
Thank you for reaching out to us regarding the UI version of TCGAbiolinks. Unfortunately, we regret to inform you that we are currently unable to provide support for this version due to competing priorities and a lack of available resources.

As a result, we have made the difficult decision to remove the UI version of TCGAbiolinks from Bioconductor. We understand that this may cause inconvenience, but please rest assured that we are committed to supporting other aspects of TCGAbiolinks as well as our other projects to the best of our abilities.

We apologize for any frustration or inconvenience this may have caused and appreciate your understanding. If you have any further questions or concerns, please don't hesitate to reach out to us.
