### ISSUE TITLE
GDCdownload

### ISSUE THREAD

**Issue by Falancios** [BioinformaticsFMRP/TCGAbiolinks#84]
Hello, this is not a really but a questio,:
 I'm developing  a project were I want to see the methylation and expression of a specific number of genes (around 20). But when I use TCGABiolinks I cant download just 1, 2 ou 3 genes. And that is my question, there is a way to download a methylation data of a specific gene?

What I did:
> query.met <- GDCquery(project = "TCGA-BRCA", 
                      legacy = TRUE,
                      data.category = "DNA methylation",
                      platform = "Illumina Human Methylation 450")

> GDCdownload(query.met) 
but data size is 18Gb this is a lot of data, because it has in it all genes and i just want a specific number of genes that contain the information fo Normal and Tumor tisue, it is possible to do that?

Thank you.
André

**Comment by tiagochst** [comment]
Hi, 
Unfortunately not with TCGAbiolinks, the files from GDC contains all genes so you will need to download the whole file. With our package, what you can do is prepare the object and then subset the data to those specific genes.

If the problem is the size, there would also be some workarounds, you can get the data from GDAC firehose using RTCGAtoolbox which is one unique file (3.5Gb) instead of one for each patient.
However, some samples from the old TCGA were removed in GDC (i.e. some because they didn't pass quality scores), and I'm not sure  GDAC firehose has the most updated dataset.

**Comment by Falancios** [comment]
Thank you for the quick answer,

my best,
André
